apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: hasnain
      app: cv
  template:
    metadata:
      labels:
        tier: hasnain
        app: cv
    spec:
      containers:
      - name: cv-manual
        image: hasnainzaib/cv
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          failureThreshold: 2
          periodSeconds: 3
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /index.html
            port: 80
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 1      
        ports:
        - containerPort: 80
          name: tcp
