apiVersion: v1
kind: Service
metadata:
  name: cv-manual
spec:
  type: NodePort
  selector:
    tier: hasnain
    app: cv
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000